# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/solana/extract-files.sh

# system/app
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/app/ChargeOnlyMode.apk:/system/app/ChargeOnlyMode.apk \
vendor/motorola/solana/proprietary/app/PhoneConfig.apk:/system/app/PhoneConfig.apk \
vendor/motorola/solana/proprietary/app/ProgramMenu.apk:/system/app/ProgramMenu.apk \
vendor/motorola/solana/proprietary/app/ProgramMenuSystem.apk:/system/app/ProgramMenuSystem.apk \

PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/bin/tf_daemon:/system/bin/tf_daemon \
vendor/motorola/solana/proprietary/bin/Hostapd:/system/bin/Hostapd \
vendor/motorola/solana/proprietary/bin/akmd2:/system/bin/akmd2 \
vendor/motorola/solana/proprietary/bin/ap_gain.bin:/system/bin/ap_gain.bin \
vendor/motorola/solana/proprietary/bin/ap_gain_mmul.bin:/system/bin/ap_gain_mmul.bin \
vendor/motorola/solana/proprietary/bin/batch:/system/bin/batch \
vendor/motorola/solana/proprietary/bin/battd:/system/bin/battd \
vendor/motorola/solana/proprietary/bin/btcmd:/system/bin/btcmd \
vendor/motorola/solana/proprietary/bin/bthelp:/system/bin/bthelp \
vendor/motorola/solana/proprietary/bin/bttest_mot:/system/bin/bttest_mot \
vendor/motorola/solana/proprietary/bin/bugtogo.sh:/system/bin/bugtogo.sh \
vendor/motorola/solana/proprietary/bin/charge_only_mode:/system/bin/charge_only_mode \
vendor/motorola/solana/proprietary/bin/chat-ril:/system/bin/chat-ril \
vendor/motorola/solana/proprietary/bin/dbvc_atvc_property_set:/system/bin/dbvc_atvc_property_set \
vendor/motorola/solana/proprietary/bin/dlnasrv:/system/bin/dlnasrv \
vendor/motorola/solana/proprietary/bin/dmt:/system/bin/dmt \
vendor/motorola/solana/proprietary/bin/dumpe2fs:/system/bin/dumpe2fs \
vendor/motorola/solana/proprietary/bin/dund:/system/bin/dund \
vendor/motorola/solana/proprietary/bin/ecckeyd:/system/bin/ecckeyd \
vendor/motorola/solana/proprietary/bin/enable_mdm_usb_suspend.sh:/system/bin/enable_mdm_usb_suspend.sh \
vendor/motorola/solana/proprietary/bin/enc_mgt_tool:/system/bin/enc_mgt_tool \
vendor/motorola/solana/proprietary/bin/encryption_test:/system/bin/encryption_test \
vendor/motorola/solana/proprietary/bin/fbread:/system/bin/fbread \
vendor/motorola/solana/proprietary/bin/ftmipcd:/system/bin/ftmipcd \
vendor/motorola/solana/proprietary/bin/gkilogd:/system/bin/gkilogd \
vendor/motorola/solana/proprietary/bin/hdcp-mknod:/system/bin/hdcp-mknod \
vendor/motorola/solana/proprietary/bin/ip:/system/bin/ip \
vendor/motorola/solana/proprietary/bin/loadpreinstalls.sh:/system/bin/loadpreinstalls.sh \
vendor/motorola/solana/proprietary/bin/mdm_panicd:/system/bin/mdm_panicd \
vendor/motorola/solana/proprietary/bin/memtest_mode:/system/bin/memtest_mode \
vendor/motorola/solana/proprietary/bin/modemlog:/system/bin/modemlog \
vendor/motorola/solana/proprietary/bin/mot_boot_mode:/system/bin/mot_boot_mode \
vendor/motorola/solana/proprietary/bin/motobox:/system/bin/motobox \
vendor/motorola/solana/proprietary/bin/napics.sh:/system/bin/napics.sh \
vendor/motorola/solana/proprietary/bin/pppd-ril:/system/bin/pppd-ril \
vendor/motorola/solana/proprietary/bin/rild:/system/bin/rild \
vendor/motorola/solana/proprietary/bin/secclkd:/system/bin/secclkd \
vendor/motorola/solana/proprietary/bin/smc_pa_ctrl:/system/bin/smc_pa_ctrl \
vendor/motorola/solana/proprietary/bin/start_enc_mgt_tool.sh:/system/bin/start_enc_mgt_tool.sh \
vendor/motorola/solana/proprietary/bin/startup_smc.sh:/system/bin/startup_smc.sh \
vendor/motorola/solana/proprietary/bin/tcmd:/system/bin/tcmd \
vendor/motorola/solana/proprietary/bin/tcmdhelp:/system/bin/tcmdhelp \
vendor/motorola/solana/proprietary/bin/testpppd:/system/bin/testpppd \
vendor/motorola/solana/proprietary/bin/tiap_loader:/system/bin/tiap_loader \
vendor/motorola/solana/proprietary/bin/tstmetainfo:/system/bin/tstmetainfo \
vendor/motorola/solana/proprietary/bin/tty2ttyd:/system/bin/tty2ttyd \
vendor/motorola/solana/proprietary/bin/tund:/system/bin/tund \
vendor/motorola/solana/proprietary/bin/usbd:/system/bin/usbd \
vendor/motorola/solana/proprietary/bin/vold:/system/bin/vold \
vendor/motorola/solana/proprietary/bin/vpnclientpm:/system/bin/vpnclientpm \
vendor/motorola/solana/proprietary/bin/whisperd:/system/bin/whisperd \

# system/etc
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/etc/01_Vendor_ti_omx.cfg:/system/etc/01_Vendor_ti_omx.cfg \
vendor/motorola/solana/proprietary/etc/backup_targets.csv:/system/etc/backup_targets.csv \
vendor/motorola/solana/proprietary/etc/btpan.conf:/system/etc/btpan.conf \
vendor/motorola/solana/proprietary/etc/dbus.conf:/system/etc/dbus.conf \
vendor/motorola/solana/proprietary/etc/ecryptfs.exc:/system/etc/ecryptfs.exc \
vendor/motorola/solana/proprietary/etc/ecryptfs.tab:/system/etc/ecryptfs.tab \
vendor/motorola/solana/proprietary/etc/event-log-tags:/system/etc/event-log-tags \
vendor/motorola/solana/proprietary/etc/excluded-input-devices.xml:/system/etc/excluded-input-devices.xml \
vendor/motorola/solana/proprietary/etc/hdmiSolDefLg.gif:/system/etc/hdmiSolDefLg.gif \
vendor/motorola/solana/proprietary/etc/hdmiSolDefSm.gif:/system/etc/hdmiSolDefSm.gif \
vendor/motorola/solana/proprietary/etc/opl.dat.enc:/system/etc/opl.dat.enc \
vendor/motorola/solana/proprietary/etc/priority_notifications_config.xml:/system/etc/priority_notifications_config.xml \
vendor/motorola/solana/proprietary/etc/pvplayer.cfg:/system/etc/pvplayer.cfg \
vendor/motorola/solana/proprietary/etc/smc_android_cfg.ini:/system/etc/smc_android_cfg.ini \
vendor/motorola/solana/proprietary/etc/smc_pa.ift:/system/etc/smc_pa.ift \
vendor/motorola/solana/proprietary/etc/smc_pa_pk_4_ipa.bin:/system/etc/smc_pa_pk_4_ipa.bin \
vendor/motorola/solana/proprietary/etc/supportedlocales.conf:/system/etc/supportedlocales.conf \

#vendor/motorola/solana/proprietary/etc/security/mancacerts.zip:/system/etc/security/mancacerts.zip \
#vendor/motorola/solana/proprietary/etc/security/oprcacerts.zip:/system/etc/security/oprcacerts.zip \
#vendor/motorola/solana/proprietary/etc/security/suplcerts.bks:/system/etc/security/suplcerts.bks \

# system/etc/(others)
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/etc/firmware/TIInit_10.5.20.bts:/system/etc/firmware/TIInit_10.5.20.bts \
vendor/motorola/solana/proprietary/etc/firmware/TIInit_10.6.15.bts:/system/etc/firmware/TIInit_10.6.15.bts \
vendor/motorola/solana/proprietary/etc/firmware/ap_bt_data.bin:/system/etc/firmware/ap_bt_data.bin \
vendor/motorola/solana/proprietary/etc/firmware/fm_rx_init_1283.2.bts:/system/etc/firmware/fm_rx_init_1283.2.bts \
vendor/motorola/solana/proprietary/etc/firmware/fmc_init_1283.2.bts:/system/etc/firmware/fmc_init_1283.2.bts \
vendor/motorola/solana/proprietary/etc/nuance/vsuite_config.xml:/system/etc/nuance/vsuite_config.xml \
vendor/motorola/solana/proprietary/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039.cfg:/system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039.cfg \
vendor/motorola/solana/proprietary/etc/omapcam/SEN2.cfg:/system/etc/omapcam/SEN2.cfg \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_cid1039_capabilities.bin:/system/etc/omapcam/module1.bak/cid1039_cid1039_capabilities.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_affw_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_affw_dcc_tuning.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_caf_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_caf_dcc_tuning.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_hllc_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_hllc_dcc_tuning.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_saf_dcc_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_saf_dcc_tuning.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_alg_adjust_rgb2rgb_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_alg_adjust_rgb2rgb_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_awb_alg_ti3_tuning.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_awb_alg_ti3_tuning.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ducati_eff_tun.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_eff_tun.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ducati_gamma.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_gamma.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ducati_lsc_2d.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_lsc_2d.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ducati_nsf_ldc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_nsf_ldc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_gbce_sw1_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_gbce_sw1_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_golden_module_calibration.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_golden_module_calibration.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_h3a_aewb_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_h3a_aewb_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_3d_lut_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_3d_lut_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_car_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_car_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cfai_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cfai_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cgs_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cgs_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_lut_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_lut_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_otf.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_otf.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_ee_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_ee_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gbce_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gbce_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gic_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gic_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_lsc_poly_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_lsc_poly_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf1_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf1_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf2_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf2_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_1_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_1_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_2_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_2_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2yuv_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2yuv_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rsz_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rsz_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_yuv444_to_yuv422_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_yuv444_to_yuv422_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_isif_clamp_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_isif_clamp_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_isif_csc_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_isif_csc_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_iss_glbce3_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_glbce3_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_iss_lbce_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_lbce_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_iss_scene_modes_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_scene_modes_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_iss_vstab_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_iss_vstab_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cac_cfg_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cac_cfg_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cfg_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cfg_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_lsc_interp.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_lsc_interp.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module1.bak/cid1039_ov8820_vnf_cfg_dcc.bin:/system/etc/omapcam/module1.bak/cid1039_ov8820_vnf_cfg_dcc.bin \
vendor/motorola/solana/proprietary/etc/omapcam/module2/cid1040_ov7739_sensor_config_dcc.bin:/system/etc/omapcam/module2/cid1040_ov7739_sensor_config_dcc.bin \
vendor/motorola/solana/proprietary/etc/ppp/peers/pppd-ril.options:/system/etc/ppp/peers/pppd-ril.options \
vendor/motorola/solana/proprietary/etc/spellchecker/en_US.aff:system/etc/spellchecker/en_US.aff \
vendor/motorola/solana/proprietary/etc/spellchecker/en_US.dic:system/etc/spellchecker/en_US.dic \
vendor/motorola/solana/proprietary/etc/spellchecker/es_ES.aff:system/etc/spellchecker/es_ES.aff \
vendor/motorola/solana/proprietary/etc/spellchecker/es_ES.dic:system/etc/spellchecker/es_ES.dic \
vendor/motorola/solana/proprietary/etc/updatecmds/google_generic_update.txt:system/etc/updatecmds/google_generic_update.txt \
vendor/motorola/solana/proprietary/etc/VideoEditorLite/mve.ini:/system/etc/VideoEditorLite/mve.ini \
vendor/motorola/solana/proprietary/etc/vsensor.d/MeaningFulLocation.vsensor:system/etc/vsensor.d/MeaningFulLocation.vsensor \
vendor/motorola/solana/proprietary/etc/wifi/fw_wlan1281.bin:/system/etc/wifi/fw_wlan1281.bin \
vendor/motorola/solana/proprietary/etc/wifi/fw_wlan1281_AP.bin:/system/etc/wifi/fw_wlan1281_AP.bin \
vendor/motorola/solana/proprietary/etc/wifi/hostapd.conf.templet:/system/etc/wifi/hostapd.conf.templet \

# system/lib
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/lib/libOMX.ITTIAM.AAC.encode.so:/system/lib/libOMX.ITTIAM.AAC.encode.so \
vendor/motorola/solana/proprietary/lib/libOMX.ITTIAM.WMA.decode.so:/system/lib/libOMX.ITTIAM.WMA.decode.so \
vendor/motorola/solana/proprietary/lib/libSwypeCore.so:/system/lib/libSwypeCore.so \
vendor/motorola/solana/proprietary/lib/libWifiAPHardware.so:/system/lib/libWifiAPHardware.so \
vendor/motorola/solana/proprietary/lib/libXmp_jni.so:/system/lib/libXmp_jni.so \
vendor/motorola/solana/proprietary/lib/libadkutils.so:/system/lib/libadkutils.so \
vendor/motorola/solana/proprietary/lib/libamcm.so:/system/lib/libamcm.so \
vendor/motorola/solana/proprietary/lib/libbattd.so:/system/lib/libbattd.so \
vendor/motorola/solana/proprietary/lib/libbcbmsg.so:/system/lib/libbcbmsg.so \
vendor/motorola/solana/proprietary/lib/libcaps.so:/system/lib/libcaps.so \
vendor/motorola/solana/proprietary/lib/libcapsjava.so:/system/lib/libcapsjava.so \
vendor/motorola/solana/proprietary/lib/libdlnahttpjni.so:/system/lib/libdlnahttpjni.so \
vendor/motorola/solana/proprietary/lib/libdlnajni.so:/system/lib/libdlnajni.so \
vendor/motorola/solana/proprietary/lib/libdlnaprofileparser.so:/system/lib/libdlnaprofileparser.so \
vendor/motorola/solana/proprietary/lib/libdlnasysjni.so:/system/lib/libdlnasysjni.so \
vendor/motorola/solana/proprietary/lib/libdmengine.so:/system/lib/libdmengine.so \
vendor/motorola/solana/proprietary/lib/libdmjavaplugin.so:/system/lib/libdmjavaplugin.so \
vendor/motorola/solana/proprietary/lib/libexempi.so:/system/lib/libexempi.so \
vendor/motorola/solana/proprietary/lib/libextdisp.so:/system/lib/libextdisp.so \
vendor/motorola/solana/proprietary/lib/libgdx.so:/system/lib/libgdx.so \
vendor/motorola/solana/proprietary/lib/libhdcp.so:/system/lib/libhdcp.so \
vendor/motorola/solana/proprietary/lib/libhdmi.so:/system/lib/libhdmi.so \
vendor/motorola/solana/proprietary/lib/libhostapd_client.so:/system/lib/libhostapd_client.so \
vendor/motorola/solana/proprietary/lib/libimage_jni.so:/system/lib/libimage_jni.so \
vendor/motorola/solana/proprietary/lib/libipsec.so:/system/lib/libipsec.so \
vendor/motorola/solana/proprietary/lib/libjanus.so:/system/lib/libjanus.so \
vendor/motorola/solana/proprietary/lib/libjni_nwp.so:/system/lib/libjni_nwp.so \
vendor/motorola/solana/proprietary/lib/libjni_pinyinime.so:/system/lib/libjni_pinyinime.so \
vendor/motorola/solana/proprietary/lib/libkpilogger.so:/system/lib/libkpilogger.so \
vendor/motorola/solana/proprietary/lib/libmediaext.so:/system/lib/libmediaext.so \
vendor/motorola/solana/proprietary/lib/libmetainfo.so:/system/lib/libmetainfo.so \
vendor/motorola/solana/proprietary/lib/libmirror.so:/system/lib/libmirror.so \
vendor/motorola/solana/proprietary/lib/libmirrorjni.so:/system/lib/libmirrorjni.so \
vendor/motorola/solana/proprietary/lib/libmot_atcmd.so:/system/lib/libmot_atcmd.so \
vendor/motorola/solana/proprietary/lib/libmot_atcmd_mflex.so:/system/lib/libmot_atcmd_mflex.so \
vendor/motorola/solana/proprietary/lib/libmot_bluetooth_jni.so:/system/lib/libmot_bluetooth_jni.so \
vendor/motorola/solana/proprietary/lib/libmot_bthid_jni.so:/system/lib/libmot_bthid_jni.so \
vendor/motorola/solana/proprietary/lib/libmot_btpan_jni.so:/system/lib/libmot_btpan_jni.so \
vendor/motorola/solana/proprietary/lib/libmot_led.so:/system/lib/libmot_led.so \
vendor/motorola/solana/proprietary/lib/libmotdrm1.so:/system/lib/libmotdrm1.so \
vendor/motorola/solana/proprietary/lib/libmotdrm1_jni.so:/system/lib/libmotdrm1_jni.so \
vendor/motorola/solana/proprietary/lib/libmoto_mdmctrl.so:/system/lib/libmoto_mdmctrl.so \
vendor/motorola/solana/proprietary/lib/libmoto_netutil.so:/system/lib/libmoto_netutil.so \
vendor/motorola/solana/proprietary/lib/libmoto_ril.so:/system/lib/libmoto_ril.so \
vendor/motorola/solana/proprietary/lib/libmotodbgutils.so:/system/lib/libmotodbgutils.so \
vendor/motorola/solana/proprietary/lib/libmtp_jni.so:/system/lib/libmtp_jni.so \
vendor/motorola/solana/proprietary/lib/libmtpstack.so:/system/lib/libmtpstack.so \
vendor/motorola/solana/proprietary/lib/libnative_renderer.so:/system/lib/libnative_renderer.so \
vendor/motorola/solana/proprietary/lib/libnativedrm1.so:/system/lib/libnativedrm1.so \
vendor/motorola/solana/proprietary/lib/libnbgm.so:/system/lib/libnbgm.so \
vendor/motorola/solana/proprietary/lib/libnetutils.so:/system/lib/libnetutils.so \
vendor/motorola/solana/proprietary/lib/libnmea.so:/system/lib/libnmea.so \
vendor/motorola/solana/proprietary/lib/libpanorama.so:/system/lib/libpanorama.so \
vendor/motorola/solana/proprietary/lib/libpanorama_jni.so:/system/lib/libpanorama_jni.so \
vendor/motorola/solana/proprietary/lib/libphotoflow.so:/system/lib/libphotoflow.so \
vendor/motorola/solana/proprietary/lib/libpkip.so:/system/lib/libpkip.so \
vendor/motorola/solana/proprietary/lib/libpppd_plugin-ril.so:/system/lib/libpppd_plugin-ril.so \
vendor/motorola/solana/proprietary/lib/libprojectM.so:/system/lib/libprojectM.so \
vendor/motorola/solana/proprietary/lib/libprovlib.so:/system/lib/libprovlib.so \
vendor/motorola/solana/proprietary/lib/libquicksec.so:/system/lib/libquicksec.so \
vendor/motorola/solana/proprietary/lib/librds_util.so:/system/lib/librds_util.so \
vendor/motorola/solana/proprietary/lib/libreference-ril.so:/system/lib/libreference-ril.so \
vendor/motorola/solana/proprietary/lib/libril.so:/system/lib/libril.so \
vendor/motorola/solana/proprietary/lib/libril_rds.so:/system/lib/libril_rds.so \
vendor/motorola/solana/proprietary/lib/libscalado.so:/system/lib/libscalado.so \
vendor/motorola/solana/proprietary/lib/libsmapi.so:/system/lib/libsmapi.so \
vendor/motorola/solana/proprietary/lib/libspellingcheckengine.so:/system/lib/libspellingcheckengine.so \
vendor/motorola/solana/proprietary/lib/libssmgr.so:/system/lib/libssmgr.so \
vendor/motorola/solana/proprietary/lib/libtalk_jni.so:/system/lib/libtalk_jni.so \
vendor/motorola/solana/proprietary/lib/libtexture_mem.so:/system/lib/libtexture_mem.so \
vendor/motorola/solana/proprietary/lib/libtf_crypto_sst.so:/system/lib/libtf_crypto_sst.so \
vendor/motorola/solana/proprietary/lib/libtpa.so:/system/lib/libtpa.so \
vendor/motorola/solana/proprietary/lib/libtpa_core.so:/system/lib/libtpa_core.so \
vendor/motorola/solana/proprietary/lib/libui3d.so:/system/lib/libui3d.so \
vendor/motorola/solana/proprietary/lib/libvideoeditorlite.so:/system/lib/libvideoeditorlite.so \
vendor/motorola/solana/proprietary/lib/libvoicesearch.so:/system/lib/libvoicesearch.so \
vendor/motorola/solana/proprietary/lib/libvorbisenc.so:/system/lib/libvorbisenc.so \
vendor/motorola/solana/proprietary/lib/libvpnclient_jni.so:/system/lib/libvpnclient_jni.so \
vendor/motorola/solana/proprietary/lib/libvsuite_mot_vs32_cmb103.so:/system/lib/libvsuite_mot_vs32_cmb103.so \
vendor/motorola/solana/proprietary/lib/libwbxmlparser.so:/system/lib/libwbxmlparser.so \
vendor/motorola/solana/proprietary/lib/libxmpcore.so:/system/lib/libxmpcore.so \

# system/lib/ducati
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/lib/ducati/Notify_MPUAPP_reroute_Test_Core1.xem3:/system/lib/ducati/Notify_MPUAPP_reroute_Test_Core1.xem3 \
vendor/motorola/solana/proprietary/lib/ducati/Notify_MPUSYS_Test_Core0.xem3:/system/lib/ducati/Notify_MPUSYS_Test_Core0.xem3 \
vendor/motorola/solana/proprietary/lib/ducati/Notify_MPUSYS_reroute_Test_Core0.xem3:/system/lib/ducati/Notify_MPUSYS_reroute_Test_Core0.xem3 \
vendor/motorola/solana/proprietary/lib/ducati/base_image_app_m3.xem3:/system/lib/ducati/base_image_app_m3.xem3 \

# system/lib/hw
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/lib/hw/gps.solana.so:/system/lib/hw/gps.solana.so \
vendor/motorola/solana/proprietary/lib/hw/lights.solana.so:/system/lib/hw/lights.solana.so \
vendor/motorola/solana/proprietary/lib/hw/sensors.solana.so:/system/lib/hw/sensors.solana.so \

# system/tts
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/tts/lang_pico/en-US_lh0_sg.bin:/system/tts/lang_pico/en-US_lh0_sg.bin \
vendor/motorola/solana/proprietary/tts/lang_pico/en-US_ta.bin:/system/tts/lang_pico/en-US_ta.bin \
vendor/motorola/solana/proprietary/tts/lang_pico/es-ES_ta.bin:/system/tts/lang_pico/es-ES_ta.bin \
vendor/motorola/solana/proprietary/tts/lang_pico/es-ES_zl0_sg.bin:/system/tts/lang_pico/es-ES_zl0_sg.bin \

# system/usr
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/usr/icu/icudt44l.dat:/system/usr/icu/icudt44l.dat \
vendor/motorola/solana/proprietary/usr/keychars/qwerty.kcm.bin:/system/usr/keychars/qwerty.kcm.bin \
vendor/motorola/solana/proprietary/usr/keychars/qwerty2.kcm.bin:/system/usr/keychars/qwerty2.kcm.bin \
vendor/motorola/solana/proprietary/usr/keychars/usb_keyboard_102_en_us.kcm.bin:/system/usr/keychars/usb_keyboard_102_en_us.kcm.bin \
vendor/motorola/solana/proprietary/usr/keylayout/AVRCP.kl:/system/usr/keylayout/AVRCP.kl \
vendor/motorola/solana/proprietary/usr/keylayout/cpcap-key.kl:/system/usr/keylayout/cpcap-key.kl \
vendor/motorola/solana/proprietary/usr/keylayout/qwerty.kl:/system/usr/keylayout/qwerty.kl \
vendor/motorola/solana/proprietary/usr/keylayout/usb_keyboard_102_en_us.kl:/system/usr/keylayout/usb_keyboard_102_en_us.kl \
vendor/motorola/solana/proprietary/usr/share/alsa/alsa.conf:/system/usr/share/alsa/alsa.conf \
vendor/motorola/solana/proprietary/usr/share/alsa/init/00main:/system/usr/share/alsa/init/00main \
vendor/motorola/solana/proprietary/usr/share/alsa/init/default:/system/usr/share/alsa/init/default \
vendor/motorola/solana/proprietary/usr/share/alsa/init/hda:/system/usr/share/alsa/init/hda \
vendor/motorola/solana/proprietary/usr/share/alsa/init/help:/system/usr/share/alsa/init/help \
vendor/motorola/solana/proprietary/usr/share/alsa/init/info:/system/usr/share/alsa/init/info \
vendor/motorola/solana/proprietary/usr/share/alsa/init/test:/system/usr/share/alsa/init/test \

# system/xbin
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/xbin/backup:/system/xbin/backup \
vendor/motorola/solana/proprietary/xbin/dexdump:/system/xbin/dexdump \
vendor/motorola/solana/proprietary/xbin/drm1_func_test:/system/xbin/drm1_func_test \
vendor/motorola/solana/proprietary/xbin/run_backup:/system/xbin/run_backup \
vendor/motorola/solana/proprietary/xbin/run_restore:/system/xbin/run_restore \
vendor/motorola/solana/proprietary/xbin/ssmgrd:/system/xbin/ssmgrd

# EGL blobs - 1.7.17 @ 4409
# Graphics
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/bin/pvrsrvinit:system/bin/pvrsrvinit \
vendor/motorola/solana/proprietary/lib/egl/libEGL_POWERVR_SGX540_120.so:system/lib/egl/libEGL_POWERVR_SGX540_120.so \
vendor/motorola/solana/proprietary/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so:system/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
vendor/motorola/solana/proprietary/lib/egl/libGLESv2_POWERVR_SGX540_120.so:system/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
vendor/motorola/solana/proprietary/lib/libglslcompiler.so:system/lib/libglslcompiler.so \
vendor/motorola/solana/proprietary/lib/libIMGegl.so:system/lib/libIMGegl.so \
vendor/motorola/solana/proprietary/lib/libpvr2d.so:system/lib/libpvr2d.so \
vendor/motorola/solana/proprietary/lib/libpvrANDROID_WSEGL.so:system/lib/libpvrANDROID_WSEGL.so \
vendor/motorola/solana/proprietary/lib/libPVRScopeServices.so:system/lib/libPVRScopeServices.so \
vendor/motorola/solana/proprietary/lib/libsrv_init.so:system/lib/libsrv_init.so \
vendor/motorola/solana/proprietary/lib/libsrv_um.so:system/lib/libsrv_um.so \
vendor/motorola/solana/proprietary/lib/libusc.so:system/lib/libusc.so \
vendor/motorola/solana/proprietary/lib/libdrm.so:system/lib/libdrm.so \

# stock libOMX files
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/lib/libarcaudiogetinfo.so:/system/lib/libarcaudiogetinfo.so \
vendor/motorola/solana/proprietary/lib/libarcomx_evrcdec_sharedlibrary.so:/system/lib/libarcomx_evrcdec_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libarcomx_qcelpdec_sharedlibrary.so:/system/lib/libarcomx_qcelpdec_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libarcomx_qcelpenc_sharedlibrary.so:/system/lib/libarcomx_qcelpenc_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libarcomx_wmadec_sharedlibrary.so:/system/lib/libarcomx_wmadec_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libarcplatform.so:/system/lib/libarcplatform.so \
vendor/motorola/solana/proprietary/lib/libarcsoft.so:/system/lib/libarcsoft.so \
vendor/motorola/solana/proprietary/lib/libarcstagefright.so:/system/lib/libarcstagefright.so \
vendor/motorola/solana/proprietary/lib/libhdr_interface.so:/system/lib/libhdr_interface.so \
vendor/motorola/solana/proprietary/lib/libomx_aacdec_sharedlibrary.so:/system/lib/libomx_aacdec_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libomx_amrdec_sharedlibrary.so:/system/lib/libomx_amrdec_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libomx_amrenc_sharedlibrary.so:/system/lib/libomx_amrenc_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libomx_arcomxcore_sharedlibrary.so:/system/lib/libomx_arcomxcore_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libomx_avcdec_sharedlibrary.so:/system/lib/libomx_avcdec_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libOMX_CoreOsal.so:/system/lib/libOMX_CoreOsal.so \
vendor/motorola/solana/proprietary/lib/libOMX_Core.so:/system/lib/libOMX_Core.so \
vendor/motorola/solana/proprietary/lib/libOMX.ITTIAM.AAC.encode.so:/system/lib/libOMX.ITTIAM.AAC.encode.so \
vendor/motorola/solana/proprietary/lib/libOMX.ITTIAM.WMA.decode.so:/system/lib/libOMX.ITTIAM.WMA.decode.so \
vendor/motorola/solana/proprietary/lib/libomx_m4vdec_sharedlibrary.so:/system/lib/libomx_m4vdec_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libomx_mp3dec_sharedlibrary.so:/system/lib/libomx_mp3dec_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libomx_proxy_common.so:/system/lib/libomx_proxy_common.so \
vendor/motorola/solana/proprietary/lib/libomx_rpc.so:/system/lib/libomx_rpc.so \
vendor/motorola/solana/proprietary/lib/libomx_sharedlibrary.so:/system/lib/libomx_sharedlibrary.so \
vendor/motorola/solana/proprietary/lib/libOMX.TI.DUCATI1.IMAGE.JPEGD.so:/system/lib/libOMX.TI.DUCATI1.IMAGE.JPEGD.so \
vendor/motorola/solana/proprietary/lib/libOMX.TI.DUCATI1.MISC.SAMPLE.so:/system/lib/libOMX.TI.DUCATI1.MISC.SAMPLE.so \
vendor/motorola/solana/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.CAMERA.so:/system/lib/libOMX.TI.DUCATI1.VIDEO.CAMERA.so \
vendor/motorola/solana/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.so:/system/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.so \
vendor/motorola/solana/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.H264D.so:/system/lib/libOMX.TI.DUCATI1.VIDEO.H264D.so \
vendor/motorola/solana/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.H264E.so:/system/lib/libOMX.TI.DUCATI1.VIDEO.H264E.so \
vendor/motorola/solana/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4D.so:/system/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4D.so \
vendor/motorola/solana/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4E.so:/system/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4E.so \
vendor/motorola/solana/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.VP6D.so:/system/lib/libOMX.TI.DUCATI1.VIDEO.VP6D.so \
vendor/motorola/solana/proprietary/lib/libOMX.TI.DUCATI1.VIDEO.VP7D.so:/system/lib/libOMX.TI.DUCATI1.VIDEO.VP7D.so \

# stock opencore libs
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/lib/libopencore_author.so:/system/lib/libopencore_author.so \
vendor/motorola/solana/proprietary/lib/libopencore_common.so:/system/lib/libopencore_common.so \
vendor/motorola/solana/proprietary/lib/libopencore_downloadreg.so:/system/lib/libopencore_downloadreg.so \
vendor/motorola/solana/proprietary/lib/libopencore_download.so:/system/lib/libopencore_download.so \
vendor/motorola/solana/proprietary/lib/libopencorehw.so:/system/lib/libopencorehw.so \
vendor/motorola/solana/proprietary/lib/libopencore_mp4localreg.so:/system/lib/libopencore_mp4localreg.so \
vendor/motorola/solana/proprietary/lib/libopencore_mp4local.so:/system/lib/libopencore_mp4local.so \
vendor/motorola/solana/proprietary/lib/libopencore_net_support.so:/system/lib/libopencore_net_support.so \
vendor/motorola/solana/proprietary/lib/libopencore_player.so:/system/lib/libopencore_player.so \
vendor/motorola/solana/proprietary/lib/libopencore_rtspreg.so:/system/lib/libopencore_rtspreg.so \
vendor/motorola/solana/proprietary/lib/libopencore_rtsp.so:/system/lib/libopencore_rtsp.so \
vendor/motorola/solana/proprietary/lib/libVendor_ti_omx_config_parser.so:/system/lib/libVendor_ti_omx_config_parser.so \
vendor/motorola/solana/proprietary/lib/libVendor_ti_omx.so:/system/lib/libVendor_ti_omx.so \

# stock camera files
PRODUCT_COPY_FILES += \
vendor/motorola/solana/proprietary/lib/libcamera.so:/system/lib/libcamera.so \
vendor/motorola/solana/proprietary/lib/libomxcameraadapter.so:/system/lib/libomxcameraadapter.so \

